repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use a recent, stable tag or commit SHA
    hooks:
      - id: trailing-whitespace
        exclude: .*\.json$|.*\.md$
      - id: end-of-file-fixer
        exclude: .*\.json$|.*\.md$
      - id: name-tests-test
      - id: flake8
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        name: Auto-Format Python Code
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Lint Python Code
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Sort Imports
